config/routes.rb
SampleApp::Application.routes.draw do

  post 'stripe/webhook'
  
  get "ex_user_comments/new"

  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]    
  resources :plans
  resources :subscriptions
  resources :users do
    member do
      get :cancel
    end
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/new',    to: 'subscriptions#new'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/addcalendar', to: 'static_pages#addcalendar'
  match '/plansandpricing', to: 'static_pages#plans'
  match '/newevent', to: 'static_pages#postevent'
  match '/events', to: 'static_pages#postevent'
  match '/downgrade_confirm', to: 'users#downgrade_confirm'
  match '/upgrade', to: 'subscriptions#edit'

  post 'subscriptions/upgrade'
  post 'subscriptions/downgrade'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
  
  def contact
  end
  
  def postevent
  	if signed_in?
  		@event = current_user.events.build
      @subscription = current_user.subscriptions.first
    else
      redirect_to root_path
  	end
  end

  def plans
    
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

    <h1>About Us</h1>
    <p>
      The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      is a project to make a book and screencasts to teach web development
      with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
      is the sample application for the tutorial.
    </p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

    <h1>Help</h1>
    <p>
      Get help on the Ruby on Rails Tutorial at the
      <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
      To get help on this sample app, see the
      <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
    </p>

app/views/static_pages/home.html.erb
<div style="background-color:#f5f5f5">
<div id="graphic">
  <div class="topblock">
  <h5>Our Event Replicator sends your event to every online calendar in Orange County.</br> <span class="orange">Automatically.</span></h5>
  	            <% if signed_in? %>
              <%= link_to "Send Event", newevent_path, 
                                class: "btn btn-large btn-success btn-home" %>
            <% else %>
              <%= link_to "See Plans & Pricing", plansandpricing_path, plan_id: 2,
                                class: "btn btn-large btn-success btn-home" %>
            <% end %>
  </div>
</div>
</div>
<div id="secondbody">
	<div class="extendedwrap">
    	<div id="second-text-block">
        <h5>Here's a full list<br /> of the event<br />calendars we use.</h5>
        <span style="margin-bottom: -20px; padding-left:5px">Are we missing something?</span><br />
      <%= link_to "Add Calendar", addcalendar_path, 
                                class: "btn btn-large btn-success btn-home", id: "nomarg" %>
      </div>
    </div>
</div>
<div id="thirdbody">
    <div class="wrap">
       <center>
            <div id="textblockbottom"><center><h5>SendEvent is the fastest
and easiest way to send your event
to 30 Orange County event calendars.
Send your event today.</h5></center>
            </div>
            <% if signed_in? %>
              <%= link_to "Send Event", newevent_path, 
                                class: "btn btn-large btn-success btn-home" %>
            <% else %>
              <%= link_to "See Plans & Pricing", plansandpricing_path, 
                                class: "btn btn-large btn-success btn-home" %>
            <% end %>
        </center>
    </div>
</div>     

app/views/static_pages/plans.html.erb
<% provide(:title, 'Plans and Pricing') %>
<% pid = params[:plan_id] %>

<div id="price-tables">
  <ul class="pricing-table pricing">
    <h1>Select a Package</h1>
    <li class="pt-column prices">
      <div class="pt-package-1">
        <div class="pt-header" style="" >
          <h2>Single</h2>
          <h3>
            <span class="pt-currency">$</span>
            <span class="pt-amount">10</span>
            <span class="pt-terms"></span>
          </h3>
        </div>
        <ul class="pt-feature-list pricing">
          <li>Send 1 Event</li>
          <li>Save time</li>
          <li>Spread Awareness</li>

          <li class="no-icon"></li>
        </ul>
      </div>
      <% if pid == 1 %>
        <div style="padding-left:40px; padding-top:10px;">
          <em>Current Plan</em>
        </div>
      <% else %>
        <div style="padding-left:40px; padding-top:10px;">
          <%= link_to "Select Plan", signup_path(:plan_id => 1),
            :class => "btn btn-large btn-success btn-home", :id => "nomarg" %>

        </div>
      <% end %>

    </li>

    <li class="pt-column prices">
      <div class="pt-package-2">
        <div class="pt-header" style="background-color: #7097C3" >
          <h2>Unlimited</h2>
          <h3>
            <span class="pt-currency">$</span>
            <span class="pt-amount">30</span>
            <span class="pt-terms">/mo</span>
          </h3>
        </div>


        <ul class="pt-feature-list pricing">
          <li>Send Unlimited Events</li>
          <li>Save time</li>
          <li>Spread Awareness</li>
          <li class="no-icon"></li>
        </ul>
      </div>
      <div style="padding-left:40px; padding-top:10px">
        <% if signed_in? %>
          <% if pid == 1 %>
            <%= link_to "Upgrade Plan", signup_path(:plan_id => 2, :downgrade => "no"),
              :class => "btn btn-large btn-success btn-home", :id => "nomarg" %>
          <% else %>
            <% if pid == 2 %>
              <em>Current Plan</em>
            <% else %>
              <%= link_to "Select Plan", signup_path(:plan_id => 2),
                :class => "btn btn-large btn-success btn-home", :id => "nomarg" %>
            <% end %>
          <% end %>
        <% else %>
          <%= link_to "Select Plan", signup_path(:plan_id => 2),
            :class => "btn btn-large btn-success btn-home", :id => "nomarg" %>
        <% end %>
      </div>

    </li>


  </ul>
</div>

app/views/static_pages/postevent.html.erb
<%= provide(:title, "Submit Event") %>
<%= current_user.name %><br />
<%= @subscription.eventsremaining %> post remaining this month.
<%= @current_user.remember_token %>
<h1>Submit Event</h1>
<% if @subscription.status == "active" %>
  <div style="width:1200px; margin:0 auto">
    <div class="row">
      <div class="span6 offset3">
        <%= form_for(@event) do |f| %>
          <%= render 'shared/error_messages', :object => f.object %>
          <div class="control-group">
            <%= f.label :name, :class => "control-label" %><br />
            <%= f.text_field :name, :value => "event name" %>
          </div>
          <div class="control-group">
            <%= f.label :startdate, :class=>"control-label" %><br />
            <%= f.text_field :startdate, :value => "startdate" %>
          </div>
          <div class="control-group">
            <%= f.label :enddate, :class => "control-label" %><br />
            <%= f.text_field :enddate, :value => "end date" %>
          </div>
          <div class="control-group">
            <%= f.label :starttime, :class => "control-label" %><br />
            <%= f.text_field :starttime, :value => "starttime" %>
          </div>
          <div class="control-group">
            <%= f.label :endtime, :class => "control-label" %><br />
            <%= f.text_field :endtime, :value => "endtime" %>
          </div>

          <div class="actions">
            <%= f.submit "Send my Event", :class => "btn btn-large btn-primary", :id => "submitacct" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% elsif @subscription.status == "inactive" %>
    <div style="width:1200px; margin:0 auto; text-align: center; color: red;">
      Your Payment is Failed. Please Update billing information.<br/>
      <%= link_to "Update Billing Info", edit_user_path(current_user.payments.first) %>
    </div>
  <% elsif @subscription.status == "notverified" %>
    <div style="width:1200px; margin:0 auto; text-align: center; color: red;">
      Your payment is not verified yet. Please wait few moments.
    </div>
  <% elsif @subscription.status == "cancelled" %>
    <div style="width:1200px; margin:0 auto; text-align: center; color: red;">
      Your subscription is cancelled.<br/>
      <%= link_to "Upgrade", upgrade_path %>
    </div>
  <% elsif @subscription.status == "none" %>
    <div style="width:1200px; margin:0 auto; text-align: center; color: red;">
      Your have no any active subscription.<br/>
      <%= link_to "Upgrade", upgrade_path %>
    </div>
  <% end %>

app/views/static_pages/sendevent.html.erb
<% provide(:title, 'Send Event') %>

<h1>Enter Event Details:</h1>
