config/routes.rb
SampleApp::Application.routes.draw do

  post 'stripe/webhook'
  
  get "ex_user_comments/new"

  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]    
  resources :plans
  resources :subscriptions
  resources :users do
    member do
      get :cancel
    end
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/new',    to: 'subscriptions#new'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/addcalendar', to: 'static_pages#addcalendar'
  match '/plansandpricing', to: 'static_pages#plans'
  match '/newevent', to: 'static_pages#postevent'
  match '/events', to: 'static_pages#postevent'
  match '/downgrade_confirm', to: 'users#downgrade_confirm'
  match '/upgrade', to: 'subscriptions#edit'

  post 'subscriptions/upgrade'
  post 'subscriptions/downgrade'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                    :integer         not null, primary key
#  name                  :string(255)
#  email                 :string(255)
#  created_at            :datetime        not null
#  updated_at            :datetime        not null
#  password_digest       :string(255)
#  remember_token        :string(255)
#  admin                 :boolean         default(FALSE)
#  stripe_customer_token :string(255)
#

# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#
class User < ActiveRecord::Base
    

  attr_accessible :subscriptions_attributes, :plan
  attr_accessible :stripe_card_token, :plan_id, :postsremaining
  attr_accessible :email, :name, :password, :password_confirmation

  belongs_to :plan
  has_many :events
  has_many :payments
  has_many :subscriptions
  #has_many :subscriptions, :autosave => true
  
  #accepts_nested_attributes_for :subscriptions

  validates :plan_id, :presence => true
  validates :email, :presence => true

  has_secure_password

  #attr_accessor :stripe_card_token, :subscription_attributes

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  before_save :validate_email_uniqueness
  after_save :user_email_sync_with_stripe

  def validate_email_uniqueness
    user = User.find_by_email(self.email)
    if user.present? && user.id != self.id
      self.errors.add :email, "has already been taken"
      return false
    else
      return true
    end
  end

  def user_email_sync_with_stripe
    payment = self.payments.first
    customer = payment.customer if payment.present?
    if customer.present? && (self.email_was != self.email || self.name_was != self.name)
      customer.email = self.email
      customer.description = self.name
      customer.save
    end
  end

  #  def save_with_payment
  #    if valid?
  #      customer = Stripe::Customer.create(
  #        email:email,
  #        plan: plan_id,
  #        card: stripe_card_token )
  #      self.stripe_customer_token = customer.id
  #      save!
  #    end
  #    rescue Stripe::InvalidRequestError => e
  #      logger.error "Stripe error while creating customer: #{e.message}"
  #      errors.add :base, "There was a problem with your credit card."
  #      false
  #  end
  #
  #  def paid_upgrade
  #    if valid?
  #      upgrade = Stripe::Charge.create(
  #        card: stripe_card_token,
  #        customer: stripe_customer_token,
  #        )
  #    end
  #  end


  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, :only => [:index, :edit, :update, :destroy, :following, :followers]
  before_filter :correct_user,   :only => [:edit, :update]
  before_filter :admin_user,     :only => :destroy
  before_filter :has_plan, :only => :new

  def index
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @subscription = @user.subscriptions.first
  end

  def new
    @user = User.new
    plan_id = params[:plan_id] || params[:user][:plan_id]
    @plan = Plan.find(plan_id)
    @user = @plan.users.build
  end

  def create
    @plan = Plan.find(params[:user][:plan_id])
    
    @user = User.new(params[:user])
    @user.payments.build(params[:payment])
    if(Rails.env == 'development' || Rails.env == 'test')
      status = 'active'
    else
      status = 'notverified'
    end
    @user.subscriptions.build(:plan_id => @plan.id, :status => status, :eventsremaining => @plan.kisses)

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the SendEvent!"
      redirect_to @user
    else
      render :new
    end
  rescue Stripe::StripeError => e
    logger.error e.message
    @payment.errors.add :base, e.message
    render :action => :new
  end

  def edit
    @user = User.find(params[:id])
    @subscription = @user.subscriptions.first
    @plan = @subscription.plan if @subscription.present?
  end

  def update
    @payment = @user.payments.first
    month = params[:payment][:"expiry_date(2i)"]
    year = params[:payment][:"expiry_date(1i)"]
    card = params[:payment][:credit_card_number]
    cvc = params[:payment][:cvc]
    if @payment.handle_billing_update(card, cvc, year, month) && @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  rescue Stripe::StripeError => e
    logger.error e.message
    @user.errors.add :base, e.message
    render 'edit'
  end

  def upgrade
    @user = current_user
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(:page => params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end

  def downgrade_confirm
    @user = current_user

  end

  def cancel
    user = current_user
    payment = user.payments.first
    payment.customer.cancel_subscription if payment.customer.subscription.present?
    subscription = user.subscriptions.first
    subscription.status = "cancelled"
    subscription.eventsremaining = 0
    subscription.plan_id = 0
    subscription.save
    redirect_to root_path
  end

  def has_plan
    if params[:plan_id].blank? 
      redirect_to plansandpricing_path
    end
  end

  private
  def correct_user
    @user = current_user
    redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com) for the given user.
	def gravatar_for(user, options = { size: 50 })
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    size = options[:size]
	    gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
	    image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/users/_form.html.erb
<% downgrade = params[:downgrade] %>


<%= form_for @user, :html => {:class => "form-inline"}, :validate => true do |f|  %>
  <%= render 'shared/error_messages', object: f.object %>
  <% if downgrade == nil %>
    <div class="control-group">
      <%= f.label :name, :class => "control-label" %>
      <%= f.text_field :name, :value => "Kenny Smith" %>
    </div>

    <div class="control-group">
      <%= f.label :email, :class => "control-label" %>
      <%= f.text_field :email, :value => "Ken.edsmith@gmail.com" %>
    </div>

    <div class="control-group">
      <%= f.label :password, :class => "control-label" %>
      <%= f.password_field :password, :value => "qwerty" %>
    </div>

    <div class="control-group">
      <%= f.label :password_confirmation, "Confirmation", :class => "control-label" %>
      <%= f.password_field :password_confirmation, :value => "qwerty" %>
    </div>

    <div class="control-group">

    </div>
  <% end %>
  <br/><br/>
  <% plan_id = params[:plan_id] || params[:user][:plan_id] %>
  <%= f.hidden_field :plan_id, :value => plan_id %>

  <%= fields_for(@payment ||= Payment.new) do |p| %>
    <%= p.hidden_field :stripe_token %>
    <%= p.hidden_field :last_4_digits %>
    <%= p.hidden_field :card_exp_month %>
    <%= p.hidden_field :card_exp_year %>
    <%= p.hidden_field :card_type %>

    <h3 class="two">Your payment information</h3>
    <div id="credit-card">
      <div id="credit-card-errors" style="display: none">
        <div id="stripe-error-message" class="alert-message block-message error"></div>
      </div>
      <div class="control-group">
        <%= label_tag :credit_card_number, "Card Number ", :class => "control-label" %>
        <%= text_field_tag :credit_card_number, params[:credit_card_number], :value => "4242424242424242", :disabled => true %>
      </div>
      <div class="control-group">
        <%= label_tag :cvv, "Security Code (CVV)", :class => "control-label" %>
        <%= text_field_tag :cvv, params[:cvv], :value => "123", :disabled => true %>
      </div>
      <div class="control-group">
        <%= label_tag :expiry_date, "Card Expiration", :class => "control-label" %>
        <%= date_select "", :expiry_date, {:discard_day => true, :order => [:month, :year], :use_month_numbers => true, :start_year => Date.today.year, :end_year => Date.today.year + 25, :disabled => true}, {:class => 'small'} %>
      </div>
    <% end %>

    <div class="control-group">
  <%#= link_to_add_fields "Subscriptions", f, :subscriptions %>
    </div>
    <%= f.submit "Create my account", class: "btn btn-large btn-primary", id: "submitacct" %>
      <div class="processing">
        <%= image_tag('white_spinner.gif') %>
      </div>
    </div>
  <% end %>

app/views/users/_subscription_fields.html.erb
<fieldset>
  <%= f.hidden_field :status, :value => "active" %><br />
  <%= f.hidden_field :plan_id, :value => params[:plan_id] %>
  <%= f.hidden_field :eventsremaining, :value => params[:plan_id] %>
</fieldset>

app/views/users/_upgrade_fields.html.erb
<fieldset>
  <%= f.hidden_field :status, :value => "active" %><br />
  <%= f.hidden_field :plan_id, :value => "2" %>
  <%= f.hidden_field :eventsremaining, :value => "1000000" %>
</fieldset>

app/views/users/_userinfo.html.erb
         <%= form_for @user, :html => {:class => "form-inline"} do |f|  %>
        <h3 class="one">Your account details</h3>
        <div class="control-group">
          <%= f.label :name, :class => "control-label" %> 
          <%= f.text_field :name %>
        </div>  

        <div class="control-group">
          <%= f.label :email, :class => "control-label" %>
          <%= f.text_field :email %>
        </div>  

        <div class="control-group">
          <%= f.label :password, :class => "control-label" %>
          <%= f.password_field :password %>
        </div>  

        <div class="control-group">
          <%= f.label :password_confirmation, "Confirmation", :class => "control-label" %>
          <%= f.password_field :password_confirmation %>
        </div>  

        <div class="control-group">  
         

app/views/users/downgrade_confirm.html.erb
<div class="GreenBlueBG">
<div style="width:1200px; margin:0 auto;">
<div class="row">
  <div class="span7 offset4">
    <h1>Cancel Plan?</h1>
    <p>We're sorry to see you go!  Please let us know if there's anything we can do to bring you back in the future.</p>
    <%= form_tag subscriptions_downgrade_path, :html => {:class => "form-inline"}  %>

    	<%= hidden_field_tag :plan_id, :value => 0 %>

    	<%= submit_tag "Downgrade my plan", class: "btn btn-large btn-danger", id: "submitacct" %>
   
    or
    <%= link_to "Cancel account", cancel_user_path(@user, :user => { :plan_id => 0 }), :confirm => "Are you Sure" %>

  </div>
  </div>
</div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 

<div class="GreenBlueBG">
  <div style="width:1200px; margin:0 auto;">
    <div class="row">
      <div class="span7 offset4">
        <h1>Update your profile</h1>
        <%= form_for @user, :html => { :class => "form-inline" } do |f| %>
          <%= render 'shared/error_messages', :object => f.object %>
          <div class="control-group">
            <%= f.label :name, :class => "control-label" %>
            <%= f.text_field :name %>
          </div>

          <div class="control-group">
            <%= f.label :email, :class => "control-label" %>
            <%= f.text_field :email %>
          </div>

          <div class="control-group">
            <%= f.label :password, :class => "control-label" %>
            <%= f.password_field :password %>
          </div>

          <div class="control-group">
            <%= f.label :password_confirmation, "Confirm Password", :class => "control-label" %>
            <%= f.password_field :password_confirmation %>
          </div>

          <div class="expan-update-billing-info">
            |<span id="expan-billing-info">+</span>|-------- Update your billing information
          </div>

          <div id="billing-update-form">
            <%= fields_for(@payment ||= Payment.new) do |p| %>
              <div class="control-group">
                <%= p.label :credit_card_number, "Card Number ", :class => "control-label" %>
                <%= p.text_field :credit_card_number %>
              </div>
              <div class="control-group">
                <%= p.label :cvc, "Security Code (CVV)", :class => "control-label" %>
                <%= p.text_field :cvc %>
              </div>
              <div class="control-group">
                <%= p.label :expiry_date, "Card Expiration", :class => "control-label" %>
                <%= p.date_select :expiry_date, {:discard_day => true, :order => [:month, :year], :use_month_numbers => true, :start_year => Date.today.year, :end_year => Date.today.year + 25}, {:class => 'small'} %>
              </div>
            <% end %>
          </div>

          <%= f.submit "Save changes", :class => "btn btn-large btn-primary", :id => "submitacct" %>
        <% end %>
        <h3 class="two">Plan Info</h3>
        <p>You are currently subscribed to the <%= @plan.name if @plan.present? %> plan, which gives you <%= pluralize(@plan.kisses, 'event') if @plan.present? %> to post this month.</p>
        <% if @subscription.present? && @subscription.plan_id == 1 %>
          <p>If you'd like to send more events this month, please select from the following options:</p>
          <div class="control-group">
            <%= link_to "Upgrade my plan ->", upgrade_path,
              :class => "btn btn-large btn-success btn-home", :id => "nomarg" %>
          </div>
        <% elsif @subscription.present? && @subscription.plan_id == 2 %>
          <div class="control-group">
            <%= link_to "Downgrade my plan ->", downgrade_confirm_path,
              :class => "btn btn-large btn-danger btn-home", :id => "nomarg" %>
          </div>
        <% elsif @subscription.present? && @subscription.plan_id == 0 %>
          <p>You have no any active subscription</p>
          <div class="control-group">
            <%= link_to "Upgrade my plan ->", upgrade_path,
              :class => "btn btn-large btn-success btn-home", :id => "nomarg" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready(function(){
    $('span#expan-billing-info').click(function(){
      $('div#billing-update-form').toggle('slow');
      var a_text = $("span#expan-billing-info").text();
      if (a_text == "+")
      {
        $('span#expan-billing-info').text('-');
      }
      else
      {
        $('span#expan-billing-info').text('+');
      }
    });

    var card = $('#payment_credit_card_number').val();
    if (card.length > 0)
    {
      $('div#billing-update-form').toggle('slow');
      var a_text = $("span#expan-billing-info").text();
      if (a_text == "+")
      {
        $('span#expan-billing-info').text('-');
      }
      else
      {
        $('span#expan-billing-info').text('+');
      }
    }
  });
</script>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% upgradetype = params[:upgradetype] %>


<div id="GraydientBackground">
<div style="width:1200px; margin:0 auto;">
<div class="row">
  <div class="span7 offset4">
    
    <h1>Selected Plan: <strong><%= @plan.name %></strong></h1>
    <p>You're signing up for the <%= @plan.name %> plan, which will allow you to send <%= @plan.kisses %> events every month!  You will be billed $<%= @plan.price %>0 on a monthly basis.</p>
    <%= render 'form' %>
  </div>
</div>
</div>
</div>

app/views/users/sendevent.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<div class="span4">
		
			<h1>
				Enter your event details and we'll automatically send your event to over 30 Orange County events calendars!
				<em>Note: You have 
				<%= @user.plan_id %>
				<%= @user.email %>
			</h1>
		</div>
</div>
<%= render 'sendevent' %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
	<div class="span4">
		
			<h1>
				<em>Note: You have <%= pluralize(@subscription.eventsremaining, 'event') %>  remaining this month.</em>
				<%= @user.email %>
				
			</h1>
		</div>
</div>

app/views/users/upgrade.html.erb
<% provide(:title, "Edit user") %> 
<% pid = params[:plan_id] %>
<% plan_object = Plan.find(pid) %>
<% if @user.plan_id == 1 %>
<% @user.plan_id = "300000" %>
<% stripecustomertoken = @user.stripe_customer_token %>
<% end %>
<%= pid %>
<div class="GreenBlueBG">
<div style="width:1200px; margin:0 auto;">
<div class="row">
  <div class="span7 offset4">
    <h1>Update your profile</h1>

        
  </div>
</div>