config/routes.rb
SampleApp::Application.routes.draw do

  post 'stripe/webhook'
  
  get "ex_user_comments/new"

  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]    
  resources :plans
  resources :subscriptions
  resources :users do
    member do
      get :cancel
    end
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/new',    to: 'subscriptions#new'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/addcalendar', to: 'static_pages#addcalendar'
  match '/plansandpricing', to: 'static_pages#plans'
  match '/newevent', to: 'static_pages#postevent'
  match '/events', to: 'static_pages#postevent'
  match '/downgrade_confirm', to: 'users#downgrade_confirm'
  match '/upgrade', to: 'subscriptions#edit'

  post 'subscriptions/upgrade'
  post 'subscriptions/downgrade'

end

app/models/plan.rb
# == Schema Information
#
# Table name: plans
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  price      :decimal(, )
#  kisses     :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Plan < ActiveRecord::Base
  attr_accessible :kisses, :name, :price

  has_many :users
  has_many :subscriptions
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @plans }
    end
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    @plan = Plan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/new
  # GET /plans/new.json
  def new
    @plan = Plan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @plan }
    end
  end

  # GET /plans/1/edit
  def edit
    @plan = Plan.find(params[:id])
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(params[:plan])

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render json: @plan, status: :created, location: @plan }
      else
        format.html { render action: "new" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /plans/1
  # PUT /plans/1.json
  def update
    @plan = Plan.find(params[:id])

    respond_to do |format|
      if @plan.update_attributes(params[:plan])
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan = Plan.find(params[:id])
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :kisses %><br />
    <%= f.number_field :kisses %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<div id="plans">
  <h1>Llama Kisses</h1>
  <% @plans.each do |plan| %>
    <div class="plan">
      <div class="name"><%= plan.name %></div>
      <div class="details">
        <div class="price">
          <%= number_to_currency plan.price, :precision => 0 %>
        </div>
        <div class="per_month">per month</div>
        <div class="kisses"><%= plan.kisses %> kisses</div>
        <div class="per_month">per month</div>
        <div class="signup">
          <%= link_to "Sign up", signup_path(:plan_id => plan.id) %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @plan.name %>
</p>

<p>
  <b>Price:</b>
  <%= @plan.price %>
</p>

<p>
  <b>Kisses:</b>
  <%= @plan.kisses %>
</p>


<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>