config/routes.rb
SampleApp::Application.routes.draw do

  post 'stripe/webhook'
  
  get "ex_user_comments/new"

  resources :sessions, only: [:new, :create, :destroy]
  resources :events, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]    
  resources :plans
  resources :subscriptions
  resources :users do
    member do
      get :cancel
    end
  end

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
      
  match '/new',    to: 'subscriptions#new'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/addcalendar', to: 'static_pages#addcalendar'
  match '/plansandpricing', to: 'static_pages#plans'
  match '/newevent', to: 'static_pages#postevent'
  match '/events', to: 'static_pages#postevent'
  match '/downgrade_confirm', to: 'users#downgrade_confirm'
  match '/upgrade', to: 'subscriptions#edit'

  post 'subscriptions/upgrade'
  post 'subscriptions/downgrade'

end

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-top">
  <div class="navbar-inner">
    <%= link_to image_tag("logofooter.png", :alt => "SendEvent"), root_path, :id => "logo" %>
  </div>
</footer>

app/views/layouts/_header.html.erb

<div id="GraydientBackground">
  <div style="width:1200px; margin:0 auto;">
<header class="navbar navbar-top">
  <div style="padding-left:20px; padding-right:20px">
      <%= link_to image_tag("logo.png", :alt => "SendEvent"), root_path, :id => "logo" %>
      <div class="container">
      <nav>
        <% if is_payform(yield(:title)) %>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Send Event", newevent_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, :method => "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Plans & Pricing", plansandpricing_path %></li>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
        <% end %>
      </nav>
    </div>
  </div>
</header>
</div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag    "jquery-ui-1.8.20.custom", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://js.stripe.com/v1/"%>
    <%= javascript_tag "Stripe.publishableKey = '#{STRIPE_PUBLIC_KEY}';"; %>


    <%= csrf_meta_tags %>
<%#= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>

    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "alert alert-#{key}") %>
      <% end %>
      <%= yield %>

    <% if is_payform(:title) %>

    <% else %>
      <%= render 'layouts/footer' %>
    <% end %>
    <%= debug(params) if Rails.env.development? %>
  </body>
  </html>